### PR TITLE
update MSYS2 install instructions, and remove locally hosted repo

### PR DESCRIPTION
**Pull request by jdtournier**
This removes the pacman repo and associated files, and updates the install instructions to fetch the package from the GitHUb 
 release and install it using `pacman -U` directly. Turns out this can be done with a rather lengthy one-liner, so it's actually just as simple as before, and allows us to keep track of download stats on GitHub.

### CODE REVIEW

**Comment by jdtournier** [comment]
One-line command tested and working on my Windows 10 laptop, by the way. 👍

**Comment by bjeurissen** [comment]
Looks good! (Can't test it myself though...)

Alternatively, we could use the same approach as the macos installer: bundling MRtrix and all dependencies in one archive. That way we have complete control over the dependencies, avoiding occasional niggles with msys2 packages or the package manager.

**Comment by jdtournier** [comment]
> Alternatively, we could use the same approach as the macos installer: bundling MRtrix and all dependencies in one archive.

No, I really don't want to go down that road. We've discussed this before, to do this we'd need to effectively bundle msys2 itself. That's bound to open up a can of worms, and besides, we'd be talking about a 2Gb+ download...

**Comment by bjeurissen** [comment]
I meant bundling everything except msys2. But I am ok with the current approach.

I was just thinking the alternative could provide a more generic way of installing across OSes. It could even work on a variety of linux distributions using a single linux tarball. But I am just thinking out loud here...

**Comment by jdtournier** [comment]
Ok, I think you've raised this before. That can work on macOS and Linux - though I'm still concerned about the GUI side of things on Linux, it'll take some effort to figure out what needs to be bundled with Qt to make it work across all distros. But on these two OS, at least we have a POSIX environment with a useable terminal, a bash (or other Unix) shell, and path handling that matches assumptions. On Windows, I don't fancy supporting users trying to use MRtrix on a DOS shell. I reckon many of our scripts probably won't work outside of the MSYS2 version of python that we use (it uses the cygwin POSIX translation layer) - though to be fair, many of our script won't work because the dependencies don't exist... But regardless, I think we need to strongly encourage users to use MSYS2 on Windows. 

On top of that, there's a good chance we might eventually switch over to WSL2 once it's released properly. So MSYS2 support might be a temporary stop-gap. It doesn't mean that we can't provide generic executables that will work even in a DOS shell, but I really don't fancy supporting users who choose to do this...

**Comment by bjeurissen** [comment]
I agree that MRtrix is pretty useless without a Unix shell. I was not suggesting we ditch msys2. My suggestion was to have users first install msys2 and then install a single tarball with MRtrix and its dependencies, without relying on the package manager (like we do in the macos installer). The major benefit would be to have complete control over the dependencies and to be able to use the same installer on multiple platforms (with one tarball per OS) and reuse the same tarball across linux distributions.

**Pull request merged**
