### PR TITLE
added dedicated download page

### PR DESCRIPTION
**Pull request by maxpietsch**
Links to the platform specific instructions to avoid visitor confrontation with the rather busy wiki page when all they want is know how to get mrtrix. Untested as I don't know how to render it without merge. Feel free to discard if deemed unnecessary.

### CODE REVIEW

**Comment by dchristiaens** [comment]
Hey Max, just a general comment: you can render the site locally if you have Ruby and Jekyll installed. It's really easy with [these instructions](http://kbroman.org/simple_site/pages/local_test.html).

**Comment by jdtournier** [comment]
Just commit straight to master for now - we're not live yet...

But once we are live, yes, local testing would be better, thanks...

**Comment by maxpietsch** [comment]
Ok thanks!

**Comment by bjeurissen** [comment]
Noticed that the destination of the download link on the website changes
once you navigate to the Community page

**Comment by jdtournier** [comment]
Yes, we @rtabbara to propagate the recent changes to the menu over to the Discourse site - they're on different servers...

**Pull request merged**
